-- Migration to add email encryption support and Supabase user mapping
-- This migration adds:
-- 1. email_hash column for searchable email lookups (SHA-256 hash)
-- 2. supabase_user_id column for Supabase Auth integration
-- 3. Makes password nullable (for Supabase-only users)
-- 4. Adds indexes for performance

-- Add email_hash column for searchable email lookups
ALTER TABLE users
ADD COLUMN IF NOT EXISTS email_hash VARCHAR(64);

-- Add supabase_user_id column for Supabase Auth integration
ALTER TABLE users
ADD COLUMN IF NOT EXISTS supabase_user_id VARCHAR(36);

-- Make password nullable (Supabase users don't have local passwords)
ALTER TABLE users
ALTER COLUMN password DROP NOT NULL;

-- Add unique constraint on email_hash
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_hash_unique ON users(email_hash) WHERE email_hash IS NOT NULL;

-- Add unique constraint on supabase_user_id
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_supabase_user_id_unique ON users(supabase_user_id) WHERE supabase_user_id IS NOT NULL;

-- Add index on supabase_user_id for lookups
CREATE INDEX IF NOT EXISTS idx_users_supabase_user_id ON users(supabase_user_id) WHERE supabase_user_id IS NOT NULL;

-- Add index on email_hash for lookups
CREATE INDEX IF NOT EXISTS idx_users_email_hash ON users(email_hash) WHERE email_hash IS NOT NULL;

-- Add comments for documentation
COMMENT ON COLUMN users.email_hash IS 'SHA-256 hash of email for searchable lookups without decrypting';
COMMENT ON COLUMN users.supabase_user_id IS 'Supabase Auth user ID (UUID) for users authenticated via Supabase';
COMMENT ON COLUMN users.password IS 'BCrypt hashed password (nullable for Supabase-only users)';

-- Note: Existing emails will be encrypted on first read/write via the EncryptedEmailConverter
-- Email hashes should be generated by the application when users are created/updated
-- Migration script to generate hashes for existing users should be run separately if needed
